
services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    # depends_on:
    #   - hardware
    restart: always

  hardware:
    privileged: true
    build:
      context: ./hardware
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    restart: always
      
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - backend
    restart: always

networks:
  app-network:
    driver: bridge