version: "1"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - hardware

  hardware:
    privileged: true
    build:
      context: ./hardware
    ports:
      - "3010:3010"
  database:
    build:
      context: ./database
    ports:
      - "3040:3040"
    volumes:
      - ./data:/app/data
      - ./data:/app/database/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
