version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env  # This will be the .env file you copy in your deployment script
    volumes:
      - ${DATA_PATH}:/data
    restart: always

  hardware:
    privileged: true
    build:
      context: ./hardware
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - .env
    restart: always

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3040:3040"
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env  # Correctly include the env_file section
    ports:
      - "3000:3000"
    restart: always

networks:
  app-network:
    driver: bridge
