version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - hardware
    restart: always
  hardware:
    privileged: true
    build:
      context: ./hardware
    ports:
      - "3010:3010"
    restart: always
      
  database:
    build:
      context: ./database
    ports:
      - "3040:3040"
    volumes:
      - ./data:/app/data
      - ./data:/app/database/data
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
